### ISSUE TITLE
Appending pikatime to the end of the panel page and positioning it dynamically

### ISSUE THREAD

**Issue by xu-chris** [Jayshua/kirby-pikatime#1]
Follow-up issue from https://forum.getkirby.com/t/pikatime-kirby-time-picker-field/2929/17
![bildschirmfoto 2016-01-01 um 16 35 57](https://cloud.githubusercontent.com/assets/980778/12071419/173233bc-b0ac-11e5-8539-0d0e46871105.png)
The reason is that the `.mainbar`-class has an `overflow-y: scroll` property that cuts off every part of the picker.

And it turns out that there are some issues with the structure field:
![bildschirmfoto 2016-01-01 um 16 53 34](https://cloud.githubusercontent.com/assets/980778/12071421/2528b5cc-b0ac-11e5-9748-47c89fc8d61c.png)

It's because of the `overflow: auto` property of the `.modal-content`-class.

Solution: append the pikatime field outside of those containers and positioning it dynamically (like the built-in `pika-lendar`).

**Comment by Jayshua** [comment]
Solution implemented, you were exactly right. Thanks!
